### ISSUE TITLE
Transform 是private不能在外部调用

### ISSUE THREAD

**Issue by zqr95518** [bm-x/PhotoView#112]
Transform 是private不能在外部调用，其实完全可以开放出来给代码直接操作旋转，放大缩小什么的动画。

**Comment by bm-x** [comment]
怎么说呢，当初做的时候变化的动画挺多问题的，基本上公开出去，不理解整个的逻辑的话会各种问题

**Comment by zqr95518** [comment]
或者封装一些简单的方法，比如旋转放大什么的也可以？不然除了人自己去操作，没法控制不太好用。
