### ISSUE TITLE
目标PhotoView的位置问题

### ISSUE THREAD

**Issue by brucetoo** [bm-x/PhotoView#19]
目标PhotoView可能存在不同的布局环境中，比如自身设置了 对应的 layout_margin值 或者 包裹其的parent GroupView有对应的padding值,就导致执行 animteFrom 或者 animateTo 目标PhotoView的位置有偏差，我这边由于不是在你原始工程上开发没法PR。
可能以下方法可以作为优化方案:
```java

        ViewGroup parent = (ViewGroup) getParent();//获取直接的父类,便于获取对应padding
        ViewGroup.MarginLayoutParams params = (ViewGroup.MarginLayoutParams) getLayoutParams(); //获取自身的margin参数

```
在`animateFrom` 方法中 change 
```java
 float ocx = info.mRect.left + info.mRect.width() / 2;
 float ocy = info.mRect.top + info.mRect.height() / 2;
 mTranslate.withTranslate(0, 0, (int) (tcx - mScaleCenter.x), (int) (tcy - mScaleCenter.y));
```
to
```java
 float ocx = info.mRect.left + info.mRect.width() / 2 - params.leftMargin - parent.getPaddingLeft();
 loat ocy = info.mRect.top + info.mRect.height() / 2 - params.topMargin - parent.getPaddingTop();
 mTranslate.withTranslate(0, 0, (int) (tcx - mScaleCenter.x - params.leftMargin - parent.getPaddingLeft()), (int) (tcy - mScaleCenter.y - params.topMargin - parent.getPaddingTop()));
```

同样在 `animateTo`方法中 change
```java
mTranslate.withTranslate(0, 0, (int) (tcx - mScaleCenter.x), (int) (tcy - mScaleCenter.y));
```
to
```java
mTranslate.withTranslate(0, 0, (int) (tcx - mScaleCenter.x - params.leftMargin - parent.getPaddingLeft()), (int) (tcy - mScaleCenter.y - params.topMargin - parent.getPaddingTop()));
```
希望这个能被作者采纳或者给出更好的适配方案..
BTW: **Nice library...**

**Comment by bm-x** [comment]
PhotoView和margin和parent的padding并不会影响动画的效果，你可以看下我demo的ImgClick这个demo，PhotoView就是设置了margin的，padding你也可以试试，是不会有什么问题的，在计算的时候已经算进去了

要是出现动画目标偏差的，你可以从这2个问题看看
1.photoview本身设置了backgroup，backgroup是一个.9图片，暂时不支持这个
2.加载网络图片，在使用ImageLoader等图片加载 工具的时候，一般情况会先给控件设置一张默认图片，这时候Photoview就开始动画了，但是默认图片的尺寸比例和你的原图并不一样，所以会有位置会有偏差，在动画过程中你设置了从网络上加载回来的图片后，会继续按原来的默认图片的位置进行动画，所以就会有偏差了

当然具体的问题我没看到你的效果所以没法确定是什么问题

**Comment by brucetoo** [comment]
你说的问题
1.没有设置任何bg
2.即使存在这个问题，第二次执行动画的时候是有缓存的啦。那应该和默认图没啥关系了。
可以是我这边嵌套有点多的问题吧..不过我加上了以上的解决方案确实就OK了..

我好像没在源码中发现计算margin或者padding的地方耶..

**Comment by bm-x** [comment]
额。刚看了下，这这样的，放大之后的那个PhotoView是必须全屏的，方法之前的margin和padding都可以设置，但是放大之后的那个必须是全屏

**Comment by brucetoo** [comment]
是的 所以我的标题叫做:目标PhotoView....就是为了考虑可能放大后的PhotoView的非全屏的逻辑.

**Comment by bm-x** [comment]
额，这个可以考虑下，等果断时间我有空先我在修改下吧

**Comment by brucetoo** [comment]
可以的.我感觉我那个解决方案是暂时的。更多复杂的情况可能还没考虑到...不过应该可以做个参考..

**Comment by bm-x** [comment]
嗯，谢了

**Comment by brucetoo** [comment]
应该是我谢谢你...-.-

**Comment by bm-x** [comment]
额，我想起来了，在做的时候原本是要做成目标photoview不必须全屏的，但是在一些情况下，比如一个LinearLayout中，2个PhotoView一个占一边完全没重叠的情况下，这时候动画就不完整没法做动画了，所以后来做的时候就做成了目标必须全屏

**Comment by brucetoo** [comment]
情况往往是考虑不全的，所以这就是开源的好处.
