### ISSUE TITLE
FIT_START模式下长图有点小问题

### ISSUE THREAD

**Issue by uccmawei** [bm-x/PhotoView#36]
FIT_START模式下，如果图片是竖向的长方形，图片加载出来后，显示最顶部的部分，正常，然后这时如果往上化大力一点，图片就会飘出去很远了，导致一片背景色，必须手动拉回来，就恢复正常。

**Comment by bm-x** [comment]
demo中的那个女神像那个有问题么

**Comment by uccmawei** [comment]
现在直接跑你的demo是没问题，但是，activity_img.xml这个布局改一下
        android:scaleType="fitStart"
        android:src="@mipmap/ccc"
这2点，然后跑就是我描述的问题的样子了，至少我的机器是这样，mi5，MIUI8，6.0

另外，如果设置了fitStart，然后图片是正常的16:9的横向照片的话，图片会定位在顶部，滑动一下，才会回到中间，这个应该可以优化一下。

**Comment by bm-x** [comment]
要是demo没问题的话，那不是很清楚你说的是什么情况，最好录个视频或者gif看看

**Comment by uccmawei** [comment]
QQ？我录个视频给你

**Comment by uccmawei** [comment]
录屏已发送到你的邮箱。

**Comment by bm-x** [comment]
你看看，应该已经修复

**Comment by uccmawei** [comment]
嗯嗯。已经修复了。
