### ISSUE TITLE
旋转问题

### ISSUE THREAD

**Issue by ansywu07** [bm-x/PhotoView#45]
1、要实现点击按钮，直接旋转图片（不通过手势），我是设置了里面的mDegrees='角度'，然后调用onUp()方法。在PAD可以正常旋转，可是到了手机端就不行了？
2、手机端如果用手势旋转一下，然后再点击按钮就可以正常旋转。每次都必须得先手势，再点按钮就行。请问，那哪部分代码是必须要执行一边才可以执行onUp啊？ 小白请教一下~

**Comment by ansywu07** [comment]
自己弄了个方法，用matrix旋转他，解决了。谢谢

**Comment by bm-x** [comment]
通过private Transform mTranslate = new Transform();
这个类的mTranslate.withRotate(0,90);
mTranslate.start();
应该就可以了
