### ISSUE TITLE
效果图的第二张，demo中貌似没有

### ISSUE THREAD

**Issue by xiaozhi003** [bm-x/PhotoView#5]
效果图第二张点击图片 是启动activity里面放一个viewpager，还是隐藏的viewpager。如果启动activity的话，貌似缩放的就不能利于lib自带的了，但是如果要自定义里面的内容，比如里面有：下载，收藏，分享按钮等，使用隐藏view显得层级太多。不知道作者如何实现的

**Comment by bm-x** [comment]
第二张效果图是公司的项目，demo是没有。实现是点击后将一个fragment添加到界面上，fragment的布局是FrameLayout，然后有一个黑色背景的ImageView,和一个ViewPager，添加的时候黑色背景的ImageView启动渐变动画，然后ViewPager的当前的ImageView启动PhotoView的animFrom()

你说的不利于lib自带，下载收藏分享这些我不明白你说的是啥意思？不知道是要实现什么，怎么会层级太多

**Comment by xiaozhi003** [comment]
ths，回复好快，懂了：)

**Comment by bm-x** [comment]
有评论后有邮件通知我qq的

**Comment by onecoders** [comment]
ViewPager的当前的ImageView启动PhotoView的animFrom()，如果移动了以后，info怎么变更？ViewPager如何设置点击事件，点击的时候隐藏呢？

**Comment by LikeAShadow** [comment]
@bm-x 有点蒙    就这个效果能不能写个demo

**Comment by bm-x** [comment]
近期忙着找工作，短期内估计没空额

**Comment by mrqatom** [comment]
为啥info没有序列化啊，怎么把info拿到啊

**Comment by bradXie1992** [comment]
@xiaozhi003 你好，有木有gif第二个效果demo，现在卡到这了，也传了info到viewpager里面，但是第二次点击第二张图的时候，图片放大的位置就会偏移！不知道怎么解决。。。

**Comment by fxsankdang** [comment]
我补充一下，实际上用自定义对话框才是最优解。

**Comment by fxsankdang** [comment]
不过大佬提的思路确实了得。

**Comment by bboyxiao1987** [comment]
当我加载本地图片一张是530 37的会报错  小图才3kb
trying to draw too large(245510280bytes) bitmap
而加载一张600 700的65kb的可以正常显示
