### ISSUE TITLE
网络图片加载，大图位置不对，动画位置也不对，不是问题#9

### ISSUE THREAD

**Issue by allnan** [bm-x/PhotoView#86]
问题：点击小图，大图位置偏下，小图放大时先往下偏一点再放大，大图缩小的时候也是，缩放到小图偏下一点的位置。
排除方式1：Glide加载bitmap，直接photoview.setImageBitmap(),这样就没有place的作用了，不起作用。
排除方式2：直接不加载网络图片，xml中设置图片资源。同样不行。
排除方式3：修改根布局，CoordinatorLayout—>Linearlayout或者RelativeLayout，都不行。但是小图外边套着一个NestedScrollview，这个没有验证有没有影响。
排除方式4：去掉动画    ----    位置对了。。就是没有动画了。

参考https://developer.android.google.cn/training/animation/zoom.html
位置可以，就是动画不顺畅。。

**Comment by bm-x** [comment]
你先看下使用demo位置是否正确
正确的话，在你的项目中，不要使用glide，直接setImageResource() 看下位置是否正确
要是setImageResource也不正确的话，你可以贴下你的布局出来

**Comment by chengwf** [comment]
我用mipmap里面的也不行，也会位移，开始以为是glide的问题，但是我把它去掉之后还是这样
[Adapter.txt](https://github.com/bm-x/PhotoView/files/1651331/Adapter.txt)
[MainActivity.txt](https://github.com/bm-x/PhotoView/files/1651341/MainActivity.txt)[布局.txt](https://github.com/bm-x/PhotoView/files/1651342/default.txt)

这是我的代码和布局文件

**Comment by bm-x** [comment]
试下demo是否错位？

**Comment by bm-x** [comment]
把MainActivity中PhotoView的margintop去掉

**Comment by chengwf** [comment]
margin去掉了，没有什么变化，就是第一次点击会偏，再点一次就正常了，头疼

**Comment by 673295195** [comment]
我大概知道你的问题了,  因为你最外层的framelayout外面还有嵌套, 我把作者的布局外面嵌套一个LinearLayout,再加一个button就会有跟你差不多的问题.  我也是碰到这个问题
